# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:SERVERLESS_ORG}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ${env:SERVERLESS_APP}
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ${env:SERVERLESS_SERVICE}

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:AWS_ROLE}

functions:
  app:
    handler: handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    firstTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DB_TABLE_USERS}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
