# serverless
org: ${env:SERVERLESS_ORG}
service: ${env:SERVERLESS_SERVICE}

# aws
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:AWS_ROLE}

# endpoints
functions:
  app:
    handler: handler.handler
    events:
      - httpApi: "*"

# db
resources:
  Resources:
    firstTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME_LOGIN}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
